apiVersion: v1
kind: ConfigMap
metadata:
  name: "logging"
  namespace: "default"
data:
  config.yml: |
      components:
        allspark-ca:
          level: error  
          modules:       
            misc:
              level: DEBUG
            server:              
              level: DEBUG      
            init:
              level: DEBUG
            store:
              level: DEBUG